using ClosedXML.Excel;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ExamBox.Services;

public sealed record ExportRow(string Student, string StudentId, string Class, string Exam, string Objective, string Theory, string Total, string Percent, string Grade, string Outcome, string Submitted);

/// <summary>Builds downloadable result sheets (Excel and PDF) from rows the admin app already shows.</summary>
public static class ResultsExporter
{
    private static readonly string[] Headers = { "#", "Student", "Student ID", "Class", "Exam", "Objective", "Theory", "Total", "Percent", "Grade", "Outcome", "Submitted" };

    public static string Grade(double percent) => percent >= 90 ? "A" : percent >= 80 ? "B" : percent >= 70 ? "C" : percent >= 60 ? "D" : "E";

    private static string[] Cells(int n, ExportRow r) =>
        new[] { n.ToString(), r.Student, r.StudentId, r.Class, r.Exam, r.Objective, r.Theory, r.Total, r.Percent, r.Grade, r.Outcome, r.Submitted };

    public static byte[] Xlsx(string title, IReadOnlyList<ExportRow> rows, bool includeExamColumn)
    {
        using var wb = new XLWorkbook();
        var ws = wb.AddWorksheet("Results");
        ws.Cell(1, 1).Value = title; ws.Cell(1, 1).Style.Font.Bold = true; ws.Cell(1, 1).Style.Font.FontSize = 14;
        ws.Cell(2, 1).Value = "Generated " + DateTime.Now.ToString("f");
        var cols = Enumerable.Range(0, Headers.Length).Where(i => includeExamColumn || i != 4).ToList();
        for (var c = 0; c < cols.Count; c++)
        {
            var cell = ws.Cell(4, c + 1);
            cell.Value = Headers[cols[c]]; cell.Style.Font.Bold = true; cell.Style.Font.FontColor = XLColor.White;
            cell.Style.Fill.BackgroundColor = XLColor.FromHtml("#1D4ED8");
        }
        for (var r = 0; r < rows.Count; r++)
        {
            var cells = Cells(r + 1, rows[r]);
            for (var c = 0; c < cols.Count; c++) ws.Cell(5 + r, c + 1).Value = cells[cols[c]];
        }
        ws.SheetView.FreezeRows(4);
        ws.Columns().AdjustToContents();
        using var ms = new MemoryStream(); wb.SaveAs(ms); return ms.ToArray();
    }

    public static byte[] Pdf(string institution, string title, string subtitle, IReadOnlyList<(string Label, string Value)> summary,
        IReadOnlyList<ExportRow> rows, bool includeExamColumn)
    {
        QuestPDF.Settings.License = LicenseType.Community;
        var cols = Enumerable.Range(0, Headers.Length).Where(i => includeExamColumn || i != 4).ToArray();
        float[] weights = { 0.5f, 2.6f, 1.5f, 1.1f, 2.4f, 1f, 0.9f, 1f, 1f, 0.8f, 1.2f, 1.9f };
        var doc = Document.Create(d => d.Page(p =>
        {
            p.Size(PageSizes.A4.Landscape()); p.Margin(28);
            p.DefaultTextStyle(x => x.FontSize(9.5f).FontColor("#0F1B3D"));
            p.Header().Column(h =>
            {
                h.Item().Text(string.IsNullOrWhiteSpace(institution) ? "ExamBox" : institution).FontSize(10).SemiBold().FontColor("#1D4ED8");
                h.Item().Text(title).FontSize(20).Bold();
                h.Item().Text(subtitle).FontSize(9.5f).FontColor("#5B6784");
                h.Item().PaddingVertical(8).Row(r =>
                {
                    foreach (var (label, value) in summary)
                        r.RelativeItem().Border(1).BorderColor("#E3E8F3").Background("#F4F7FC").Padding(8).Column(c =>
                        {
                            c.Item().Text(value).FontSize(15).Bold().FontColor("#1D4ED8");
                            c.Item().Text(label).FontSize(8.5f).FontColor("#5B6784");
                        });
                });
            });
            p.Content().Table(t =>
            {
                t.ColumnsDefinition(c => { foreach (var i in cols) c.RelativeColumn(weights[i]); });
                t.Header(h =>
                {
                    foreach (var i in cols)
                        h.Cell().Background("#1D4ED8").Padding(5).Text(Headers[i]).FontColor("#FFFFFF").SemiBold();
                });
                for (var n = 0; n < rows.Count; n++)
                {
                    var cells = Cells(n + 1, rows[n]);
                    var bg = n % 2 == 0 ? "#FFFFFF" : "#F7F9FD";
                    foreach (var i in cols)
                    {
                        var text = t.Cell().Background(bg).BorderBottom(0.5f).BorderColor("#E3E8F3").Padding(5).Text(cells[i]);
                        if (i == 10) text.SemiBold().FontColor(cells[i] == "Pass" ? "#0F9D58" : cells[i] == "Fail" ? "#D93025" : "#B36B00");
                    }
                }
            });
            p.Footer().Row(f =>
            {
                f.RelativeItem().Text("Generated by ExamBox on " + DateTime.Now.ToString("f")).FontSize(8).FontColor("#5B6784");
                f.AutoItem().Text(x => { x.Span("Page ").FontSize(8); x.CurrentPageNumber().FontSize(8); x.Span(" of ").FontSize(8); x.TotalPages().FontSize(8); });
            });
        }));
        return doc.GeneratePdf();
    }
}
